version: '3'
services:
  samba:
    image: pangu/samba:latest
    container_name: samba
    hostname: sambaserver
    network_mode: bridge
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    tmpfs:
      - /tmp    
    volumes:
      - /opt/docker-persistence/samba/etc/smb.conf:/etc/samba/smb.conf:ro
      - /opt/docker-persistence/samba/etc/user.map:/etc/samba/user.map:ro
      - /opt/docker-persistence/samba/start.sh:/start.sh:ro
      - /opt/docker-persistence/samba/log:/var/log/samba
      - /mnt/rdmdisk:/share:z
    command: "bash /start.sh"