version: '3'
services:
  emby:
    image: emby/embyserver:latest
    container_name: embyserver
    hostname: embyserver
    #runtime: nvidia # Expose NVIDIA GPUs
    #network_mode: host # Enable DLNA and Wake-on-Lan
    network_mode: bridge
    environment:
      - UID=0 # The UID to run emby as (default: 2)
      - GID=0 # The GID to run emby as (default 2)
      - GIDLIST=0 # A comma-separated list of additional GIDs to run emby as (default: 2)
    #restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime
      - /opt/docker-persistence/emby/config:/config # Configuration directory
      - /mnt/nasdisk/03.Media:/mnt/media1 # Media directory
      - /mnt/rdmdisk/myserver/downloads/transmission/downloads/complete:/mnt/media2 # Media directory
    ports:
      - "8096:8096/tcp" # HTTP port
      #- "8920:8920/tcp" # HTTPS port
    devices:
      - /dev/dri:/dev/dri # VAAPI/NVDEC/NVENC render nodes
      #- /dev/vchiq:/dev/vchiq # MMAL/OMX on Raspberry Pi
