version: '3'
services:
  speedtest:
    image: adolfintel/speedtest:latest
    container_name: speedtest
    hostname: speedtest
    restart: unless-stopped
    network_mode: bridge
    ports:
      - "18080:80/tcp"
