version: '3'
services:
  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    hostname: transmission
    network_mode: bridge
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      #- TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=transmission #optional
      - PASS=rabbit3126 #optional
#      - WHITELIST=iplist #optional
#      - PEERPORT=peerport #optional
#      - HOST_WHITELIST=dnsnane list #optional
    volumes:
      - /mnt/rdmdisk/myserver/downloads/transmission/config:/config
      - /mnt/rdmdisk/myserver/downloads/transmission/downloads:/downloads
      - /mnt/rdmdisk/myserver/downloads/transmission/watch:/watch
    ports:
      - "9091:9091/tcp"
      - "51413:51413/tcp"
      - "51413:51413/udp"
    logging:
      driver: json-file
      options:
        max-size: "30m"
        max-file: "3"